#initialize sample
# I'm assuming that you are running in a batch mode, where the input samples have been split into 10 event chunks
# "sample" is determined by your joblist.txt file. Edit your joblist to submit a condor job per file.
# Or remove this feature out if you just want to submit one job.
sample = 000

# path to files that are copied to worker node
# change your paths to the appropriate location
input_file_name = output_sim_neutronGun_0_50_gen.$(sample).slcio
input_file_path = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/samples/neutronGun_feb5_2026/sim/$(input_file_name)
digi_reco_script = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/condor_scripts/v2.11-amd64/reconstruction/digi_reco_condor.py
pandoraSettings_path = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/condor_scripts/v2.11-amd64/reconstruction/PandoraSettings

# these you should have ready from the tutorial https://mcd-wiki.web.cern.ch/software/howto/maia/
# maia_GEO = /scratch/gregorypenn/lccontent/maia_Geometry/MAIA_versions/v1_jun27/detector-simulation/geometries/MAIA_v0
myBIBUtils_path = /scratch/gregorypenn/MyBIBUtils
# ACTSTracking_path = /scratch/gregorypenn/ACTSTracking

Universe = Vanilla
+SingularityImage = "/cvmfs/unpacked.cern.ch/ghcr.io/muoncollidersoft/mucoll-sim-ubuntu24:v2.11-amd64"
Executable     = reco.sh
Requirements = ( HAS_SINGULARITY ) && ( HAS_CVMFS_unpacked_cern_ch ) && ( HAS_CVMFS_public_uc_osgstorage_org ) && (!Regexp("^mendel", Machine))
should_transfer_files = YES
Output  = output.out.$(Cluster)-$(Process)
Log     = log.$(Cluster)
Error   = error.out.$(Cluster)-$(Process)
stream_output = True
stream_error  = True
transfer_input_files = $(input_file_path), $(digi_reco_script), $(myBIBUtils_path), $(pandoraSettings_path)
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_disk = 1GB
request_memory = 5 GB
retry_request_memory = 10 GB 
+JobDurationCategory = "Long"
+ProjectName="collab.futurecolliders"
# update this path
Executable = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/condor_scripts/v2.11-amd64/reconstruction/reco.sh
Arguments = "--inputFile $(input_file_name)"

# queue many jobs, determined by joblist.txt
Queue sample from joblist.txt  