sample = 1

input_file_path = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/samples/timeTest/piplus_gen_$(sample).slcio
input_file_name = piplus_gen_$(sample).slcio
sim_script = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/simulation/steer_sim_tau_gun_MAIA.py
maia_GEO = /scratch/gregorypenn/lccontent/maia_Geometry/detector-simulation/geometries/MAIA_v0

Universe = Vanilla
+SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/muon-collider/mucoll-deploy/mucoll:2.9-alma9"
#maybe try: /cvmfs/unpacked.cern.ch/ghcr.io/muoncollidersoft/mucoll-sim-alma9:latest
Executable     = sim.sh
# unfortunately this job will crash on CRUSH-OSG-C7 machines. Temporary fix.
Requirements = ( HAS_SINGULARITY ) && ( HAS_CVMFS_unpacked_cern_ch ) && (!Regexp("^CRUSH-OSG-C7", Machine))
should_transfer_files = YES
Output  = output.out.$(Cluster)-$(Process)
Log     = log.$(Cluster)
Error   = error.out.$(Cluster)-$(Process)
transfer_input_files = $(input_file_path), $(sim_script), $(maia_GEO)
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_disk = 5 GB
request_memory = 5 GB
+ProjectName="collab.futurecolliders"
Executable = /scratch/gregorypenn/muColl-Taus/taus/MuColl-PFlow/condor_scripts/alma9/simulation/sim.sh
Arguments = --inputFile $(input_file_name)